CREATE TABLE IF NOT EXISTS verifier_criteria (
    task_id VARCHAR(36) NOT NULL PRIMARY KEY REFERENCES task_flows(id) ON DELETE CASCADE,
    criteria TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
