"""Conversation Engine — chit-chat routing with pure LLM responses.

No rule-based/canned responses. All conversation goes through the configured
LLM provider (DeepSeek direct).

``is_chitchat_or_noise()`` remains for IntentRouter integration.
"""

from __future__ import annotations

from typing import Any

from antigona.context.builder import ContextBuilder
from antigona.providers.base import BaseProvider

__all__ = [
    "ConversationEngine",
    "chitchat_reply",
    "is_chitchat_or_noise",
]


# ─── Heuristic noise/chit-chat detector ───────────────────────────────────────
# Used by IntentRouter — kept as-is, not part of response generation.


def is_chitchat_or_noise(text: str) -> bool:
    """Heuristically decide if a message is small talk / noise, not a task."""
    stripped = text.strip()
    if not stripped or len(stripped) <= 3:
        return True
    return False


# ─── Conversation Engine ──────────────────────────────────────────────────────


class ConversationEngine:
    """Handles chit-chat messages by forwarding to an LLM provider.

    No rule-based responses. Every message goes to the provider.
    """

    def __init__(
        self,
        provider: BaseProvider | None = None,
        context_builder: ContextBuilder | None = None,
        long_term_memory: Any | None = None,
    ) -> None:
        self.provider: BaseProvider | None = provider
        self.context_builder: ContextBuilder = context_builder or ContextBuilder(
            long_term_memory=long_term_memory,
        )
        self.last_context: dict[str, Any] = {}

    def reply(self, text: str, context: dict[str, Any] | None = None) -> str:
        """Forward a chit-chat message to the LLM provider.

        Args:
            text: The user's message text.
            context: Optional context dict.

        Returns:
            A response string generated by the LLM.

        Raises:
            RuntimeError: If no provider is configured and get_default_provider()
                also returns None.
        """
        if context:
            self.last_context = context

        stripped = text.strip()
        if not stripped:
            return "..."

        from antigona.providers.resolver import ProviderResolver

        provider = self.provider or ProviderResolver.get_provider()
        if provider is None:
            raise ValueError(
                "No active LLM provider is configured. Use /providers or /setllm <provider>."
            )

        return self._generate_with_provider(text, provider=provider)

    def reply_with_provider(
        self,
        text: str,
        provider: BaseProvider | None = None,
        context: dict[str, Any] | None = None,
    ) -> str:
        """Generate a response using the given provider.

        Args:
            text: The user's message text.
            provider: Provider instance for generation.
            context: Optional context dict.

        Returns:
            A response string.

        Raises:
            ValueError: If provider is None.
        """
        if provider is None:
            raise ValueError("provider is required")

        ctx = context if context is not None else self.last_context
        turn_buffer = ctx.get("turn_buffer")

        if turn_buffer:
            messages = self.context_builder.build(
                turn_buffer=turn_buffer,
                session_summary=ctx.get("session_summary", ""),
            )
            if not messages or messages[-1].get("content") != text:
                messages.append({"role": "user", "content": text})
        else:
            messages = self.context_builder.build()
            messages.append({"role": "user", "content": text})

        return provider.generate(messages)

    def _generate_with_provider(
        self,
        text: str,
        provider: BaseProvider | None = None,
    ) -> str:
        from antigona.providers.resolver import ProviderResolver

        prov = provider or self.provider or ProviderResolver.get_provider()
        if prov is None:
            raise ValueError(
                "No active LLM provider is configured. Use /providers or /setllm <provider>."
            )
        return self.reply_with_provider(text, provider=prov)


def chitchat_reply(
    text: str,
    provider: BaseProvider | None = None,
    context: dict[str, Any] | None = None,
    long_term_memory: Any | None = None,
    file_memory: Any | None = None,
) -> str:
    """Produce an LLM response for a chit-chat message.

    Args:
        text: The user's message text.
        provider: Optional provider. If None, uses get_default_provider().
        context: Optional context dict (turn_buffer, session_summary, etc.).
        long_term_memory: Deprecated, use file_memory.
        file_memory: Optional FileMemory instance for MEMORY.md/USER.md snapshot.

    Returns:
        A response string generated by the LLM.

    Raises:
        RuntimeError: If no provider is available (no key configured).
    """
    engine = ConversationEngine(
        provider=provider,
        long_term_memory=long_term_memory,
    )
    if file_memory and engine.context_builder:
        engine.context_builder.file_memory = file_memory
        engine.context_builder._frozen_memory = file_memory.get_snapshot()
    return engine.reply(text, context=context)
